version: '3'

services:
  app:
    build: .
    volumes:
      - .:/go/src/
      - /var/log/:/var/log/
    ports:
      - "9258:9258"
    restart: always
    environment:
      - TZ=America/Sao_Paulo
